In [1]:
#join dataFrame and matrices together
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
#concatenate in numpy
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
#concatenate along axis 1
#repeat on same matrix
np.concatenate([arr1,arr1],axis =1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis =0)# concatenate along the top to bottom

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#in pandas
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index =['X','Y'])
ser1
ser2

X    3
Y    4
dtype: int64

In [10]:
ser1

T    0
U    1
V    2
dtype: int64

In [11]:
#concatenate in pandas, together
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
#specify the axis
#create a DataFrame
pd.concat([ser1,ser2],axis = 1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [13]:
#add marker or keys , we can do by using index heirarchy
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
#in dataFrame
dFrame1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dFrame2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [15]:
dFrame1

X         Y         Z
0 -0.563717 -0.082661  0.942405
1  0.277357 -2.420731  0.718793
2  0.828388 -0.602506  0.327234
3  1.230095 -0.334491 -0.521986

In [16]:
dFrame2

Y         Q         X
0 -0.573496 -0.458315 -0.498862
1 -1.165305  0.166561 -0.124659
2  0.820991 -1.781660 -0.144399

In [17]:
#make sure you run it through a list
#binds together for each dataframe had no value
pd.concat([dFrame1,dFrame2])

Q         X         Y         Z
0       NaN -0.563717 -0.082661  0.942405
1       NaN  0.277357 -2.420731  0.718793
2       NaN  0.828388 -0.602506  0.327234
3       NaN  1.230095 -0.334491 -0.521986
0 -0.458315 -0.498862 -0.573496       NaN
1  0.166561 -0.124659 -1.165305       NaN
2 -1.781660 -0.144399  0.820991       NaN

In [18]:
#we can get rid of index
pd.concat([dFrame1,dFrame2],ignore_index = True)

Q         X         Y         Z
0       NaN -0.563717 -0.082661  0.942405
1       NaN  0.277357 -2.420731  0.718793
2       NaN  0.828388 -0.602506  0.327234
3       NaN  1.230095 -0.334491 -0.521986
4 -0.458315 -0.498862 -0.573496       NaN
5  0.166561 -0.124659 -1.165305       NaN
6 -1.781660 -0.144399  0.820991       NaN

In [ ]:
#for more information
url ='http://pandas.pydata.org/pandas-docs/stable/merging.html'
url1 = 'http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'