In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr # show the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#call a value at an index
arr[8]

8

In [5]:
#get values in a particular range,upto 5
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
#set a value in an index range
arr[0:5] = 100

In [8]:
arr # values are set to 100

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
#reset the array
arr = np.arange(0,11)

In [10]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#slices of arr
sliceOfArr = arr[0:6]
sliceOfArr

array([0, 1, 2, 3, 4, 5])

In [12]:
#chnge the slice, : select all the values in the arr
sliceOfArr[:] = 99
sliceOfArr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr # one copy of array , hence if you grab a slice and
#change the vlaue it change the values

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
# to make a copy explictly
arrCopy = arr.copy()

In [15]:
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
#indexing in a 2d array
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
# to see the row , it is the second row because it is 1
arr2d[1]

array([20, 25, 30])

In [19]:
arr2d[0]

array([ 5, 10, 15])

In [20]:
#individual element value, index row (1)and index column(0)
arr2d[1][0]

20

In [22]:
#2d array slicing , 1 column index and after that ,and cut to :2
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
# it is upto one row and starting from one column
arr2d[:1,1:]

array([[10, 15]])

In [25]:
arr2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [26]:
#fancy indexing
arr2d = np.zeros((10,10))

In [27]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
#length of the array
arrLength = arr2d.shape[1]

In [30]:
arrLength

10L

In [33]:
# change the value in every value in the row
for i in range(arrLength):
    arr2d[i] = i
    

In [34]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [35]:
#fancy indexing returns the rows what ois being indexed and it
#can be in any order
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [36]:
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])