In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myArray',arr) # to save an array

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('myArray.npy') # to load you have to call the extension

array([0, 1, 2, 3, 4])

In [9]:
#save multiple arrays
arr1 = np.load('myArray.npy')
arr1

array([0, 1, 2, 3, 4])

In [10]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# to save two arrays. need a zip file
np.savez('zipArray.npz',x = arr1,y=arr2)

In [12]:
archiveArray = np.load('zipArray.npz')

In [13]:
archiveArray

In [14]:
# to look at the first array as it is saved as x
archiveArray['x']

array([0, 1, 2, 3, 4])

In [15]:
archiveArray['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#save and load text files
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#save as a text file
np.savetxt('myTextArray.txt',arr,delimiter=',')

In [18]:
arr = np.loadtxt('myTextArray.txt',delimiter=',') # to load

In [19]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])