In [1]:
import numpy as np

In [2]:
myList1 = [1,2,3,4]

In [3]:
myArray1 = np.array(myList1)

In [4]:
myArray1

array([1, 2, 3, 4])

In [5]:
myList2 = [11,22,33,44]

In [6]:
myLists = [myList1,myList2]

In [7]:
myArray2 = np.array(myLists)

In [10]:
myArray2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
myArray2.shape

(2L, 4L)

In [12]:
#datatype
myArray2.dtype

dtype('int32')

In [13]:
#special case arrays,floating type
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
myZerosArray = np.zeros(5)
#check type
myZerosArray.dtype

dtype('float64')

In [15]:
#special case of 1
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
#empty array
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
#identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
#array start ,stop ,creat even value
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5)