In [2]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#basic function apply in an array
np.sqrt(arr) #taking sqaure root of every element in array

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
#exponenetial
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
#binary functions require two array
A = np.random.randn(10)# random array with 10 random distribution

In [10]:
A

array([ 1.0166286 , -1.9110899 ,  1.51305158,  0.20398802,  0.27861013,
       -0.07382609, -0.74896013, -0.30234295,  0.65593932,  1.22099084])

In [11]:
B = np.random.randn(10)

In [12]:
B

array([-1.01521213,  0.77850484, -0.11219605, -0.34307685,  1.16990707,
       -0.18223456, -0.17975597,  0.9205964 ,  1.3759355 ,  2.14437101])

In [13]:
#add two values
np.add(A,B)

array([  1.41646897e-03,  -1.13258506e+00,   1.40085553e+00,
        -1.39088827e-01,   1.44851720e+00,  -2.56060658e-01,
        -9.28716091e-01,   6.18253446e-01,   2.03187482e+00,
         3.36536185e+00])

In [14]:
#find the max or min between two arrays comparing a and b
np.maximum(A,B)

array([ 1.0166286 ,  0.77850484,  1.51305158,  0.20398802,  1.16990707,
       -0.07382609, -0.17975597,  0.9205964 ,  1.3759355 ,  2.14437101])

In [15]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True