In [1]:
import numpy as np # saves typing numpy again and again

In [3]:
5.0/2

2.5

In [8]:
#import from future # for python 2 to get decimal division make sure
#there are two underscores before and after
from __future__ import division 

In [10]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]]) # multi dimensional array

In [11]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [12]:
#multiply array at the same spot e.g. 1*1 ,2*2 etc
arr1* arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [13]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
#arithmetic operations on array reciporocal division
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [15]:
#exponential operation
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])