##### We wish to find rules of the type If a person buys product X, then they are likely to purchase product Y.

In [2]:
import numpy as np
X = np.loadtxt(r"C:\Users\piush\Desktop\Data Science Books\Python\LEARNING_DATA_MINING_WITH_PYTHON\9781784396053_code\Code_REWRITE\Chapter 1\affinity_dataset.txt")

In [5]:
nSamples, nFeatures = X.shape
print("The dataset has {0} samples and {1} features".format(nSamples,nFeatures))

The dataset has 100 samples and 5 features


In [7]:
print(X[:5])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]


The dataset can be read by looking at each row (horizontal line) at a time. The first
row (0, 0, 1, 1, 1) shows the items purchased in the first transaction. Each
column (vertical row) represents each of the items. They are bread, milk, cheese,
apples, and bananas, respectively. Therefore, in the first transaction, the person
bought cheese, apples, and bananas, but not bread or milk.
Each of these features contain binary values, stating only whether the items were
purchased and not how many of them were purchased. A 1 indicates that "at least
1" item was bought of this type, while a 0 indicates that absolutely none of that item
was purchased.

###### we will compute the support and confidence for the rule if a person buys apples, they also buy bananas

In [8]:
numApplePurchases = 0
for i in X:
    if i[3] == 1 : #Person bought apples
        numApplePurchases +=1
        
print("{} people bought apples".format(numApplePurchases))

36 people bought apples


In [13]:
ruleValid = 0
ruleInvalid = 0
for i in X:
    if i[3] == 1:
        if i[4] == 1:
            ruleValid += 1
        else:
            ruleInvalid += 1
print("{} cases of the rule being Valid were discovered".format(ruleValid))
print("{} cases of the rule being Invalid were discovered".format(ruleInvalid))

21 cases of the rule being Valid were discovered
15 cases of the rule being Invalid were discovered


In [14]:
support = ruleValid
confidence = ruleValid / numApplePurchases

print("The support is {} and the cofidence is {} ".format(support,confidence))

The support is 21 and the cofidence is 0.5833333333333334 


In [16]:
from collections import defaultdict

#Compute for all possible rules
validRules = defaultdict(int)
invalidRules = defaultdict(int)
numOccurances = defaultdict(int)

for i in X:
    for premise in range(nFeatures):
        if i[premise] == 0: continue
        numOccurances[premise] += 1
        for conclusion in range(nFeatures):
            if premise == conclusion:
                continue
            if i[conclusion] == 1:
                validRules[(premise,conclusion)] += 1
            else:
                invalidRules[(premise,conclusion)] += 1
                
support = validRules
confidence = defaultdict(float)

for premise,conclusion in validRules.keys():
    confidence[(premise,conclusion)] = validRules[(premise,conclusion)]/numOccurances[premise]

In [18]:
features = ["bread", "milk", "cheese", "apples","banana"]
for premise,conclusion in confidence:
    premiseName = features[premise]
    conclusionName = features[conclusion]
    print("Rule: if preson buys {} , they will also buy {}".format(premiseName,conclusionName))
    print("- Confidence: {0:.3f}".format(confidence[(premise,conclusion)]))
    print("- Support: {}".format(support[(premise,conclusion)]))

Rule: if preson buys bread , they will also buy milk
- Confidence: 0.519
- Support: 14
Rule: if preson buys milk , they will also buy cheese
- Confidence: 0.152
- Support: 7
Rule: if preson buys apples , they will also buy cheese
- Confidence: 0.694
- Support: 25
Rule: if preson buys milk , they will also buy apples
- Confidence: 0.196
- Support: 9
Rule: if preson buys bread , they will also buy apples
- Confidence: 0.185
- Support: 5
Rule: if preson buys apples , they will also buy bread
- Confidence: 0.139
- Support: 5
Rule: if preson buys apples , they will also buy banana
- Confidence: 0.583
- Support: 21
Rule: if preson buys apples , they will also buy milk
- Confidence: 0.250
- Support: 9
Rule: if preson buys milk , they will also buy banana
- Confidence: 0.413
- Support: 19
Rule: if preson buys cheese , they will also buy banana
- Confidence: 0.659
- Support: 27
Rule: if preson buys cheese , they will also buy bread
- Confidence: 0.098
- Support: 4
Rule: if preson buys cheese , 

Now that we can compute the support and confidence of all rules, we want to be able
to find the best rules. To do this, we perform a ranking and print the ones with the
highest values. We can do this for both the support and confidence values.
To find the rules with the highest support, we first sort the support dictionary.

In [19]:
from operator import itemgetter
sortedSupport = sorted(support.items(),key = itemgetter(1),reverse = True)

In [21]:
for index in range(5):
    print("Rule #{}".format(index + 1))
    (premise,conclusion) = sortedSupport[index][0]
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0} they will also buy {1}".format(premise_name, conclusion_name))
    print(" - Confidence: {0:.3f}".format(confidence[(premise, conclusion)]))
    print(" - Support: {0}".format(support[(premise, conclusion)]))
    print("")

Rule #1
Rule: If a person buys cheese they will also buy banana
 - Confidence: 0.659
 - Support: 27

Rule #2
Rule: If a person buys banana they will also buy cheese
 - Confidence: 0.458
 - Support: 27

Rule #3
Rule: If a person buys apples they will also buy cheese
 - Confidence: 0.694
 - Support: 25

Rule #4
Rule: If a person buys cheese they will also buy apples
 - Confidence: 0.610
 - Support: 25

Rule #5
Rule: If a person buys banana they will also buy apples
 - Confidence: 0.356
 - Support: 21

